"""orders fixed

Revision ID: 67cf251428b8
Revises: d4e1a6cc422e
Create Date: 2023-10-26 15:58:15.194197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67cf251428b8'
down_revision: Union[str, None] = 'd4e1a6cc422e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_products_fkey', 'cart', type_='foreignkey')
    op.drop_constraint('cart_orders_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'products', ['products'], ['id'])
    op.create_foreign_key(None, 'cart', 'orders', ['orders'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_orders_fkey', 'cart', 'orders', ['orders'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cart_products_fkey', 'cart', 'products', ['products'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
