"""cart fixed

Revision ID: d4e1a6cc422e
Revises: a1d001444e08
Create Date: 2023-10-26 15:55:01.948341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e1a6cc422e'
down_revision: Union[str, None] = 'a1d001444e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'products',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart', 'orders',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('cart_products_fkey', 'cart', type_='foreignkey')
    op.drop_constraint('cart_orders_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'orders', ['orders'], ['id'],ondelete='CASCADE')
    op.create_foreign_key(None, 'cart', 'products', ['products'], ['id'],ondelete='CASCADE')
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_role_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_role_fkey', 'users', 'roles', ['role'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_orders_fkey', 'cart', 'orders', ['orders'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cart_products_fkey', 'cart', 'products', ['products'], ['id'], ondelete='CASCADE')
    op.alter_column('cart', 'orders',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart', 'products',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
