"""association table fixed 

Revision ID: e35a7dc16a7d
Revises: 67cf251428b8
Create Date: 2023-10-30 23:29:36.306861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35a7dc16a7d'
down_revision: Union[str, None] = '67cf251428b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'id')
    op.drop_column('cart', 'product_price')
    op.drop_column('cart', 'product_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('product_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
